fix: added npm audit and sonarqube fixes
contentstack/webhook-listener pull request #3
Opened 2022-09-22 16:00 UTC by vkalta

2022-10-28 12:33 UTC, netrajpatel requested changes
@vkalta Update package versions

2022-10-28 15:52 UTC, aravindbuilt approved these changes

2022-10-28 15:52 UTC, aravindbuilt approved these changes

2022-10-30 20:58 UTC, vkalta commented
> fix: updated version

@netrajpatel Done

2022-10-31 10:21 UTC, netrajpatel approved these changes

2022-10-31 12:40 UTC, merged